---
baseURL: "/manual/develop/"
languageCode: "en-us"
title: "Camunda 中文站"
theme: "camunda"

blackfriday:
  plainIDAnchors: true

params:
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Camunda Platform"
      url: "/manual"
    - id: "optimize"
      name: "Optimize"
      url: "/optimize"
    - id: 'cawemo'
      name: 'Cawemo'
      url: '/cawemo'
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "manual"
    version: "develop"
    versionAlias: "7.16"
    versions:
      - "develop"
  github:
    repositoryName: "zoollcar/camunda-docs-manual-cn"
    branch: "master"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
